### ISSUE TITLE
`TypeError: Can't convert 'Urgency' object to str implicitly`

### ISSUE THREAD

**Issue by mr-islam** [navedcoded/eyecare-daemon#6]
I was testing the master branch for the first time - basically your fork with just the OSX removed - and got this error: 

```
Traceback (most recent call last):
  File "eyecare.py", line 32, in <module>
    s.call([command, warning_urgency, expiration, warning_title, warning_message])
  File "/home/naved/anaconda3/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/naved/anaconda3/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/home/naved/anaconda3/lib/python3.5/subprocess.py", line 1483, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'Urgency' object to str implicitly
```

To be honest, I don't understand what it's saying; maybe it's something with my Python setup? I tried removing the `warning_urgency` and `success_urgency` from the `s.call`, and then it worked fine. Any ideas?

**Comment by ragerin** [comment]
Okay, so I think you should be able to wrap the urgency variables inside
the str() function, thus explicitly converting the values to a string. If
not, maybe implementing **str** method in the Urgency global class. Are you
using python2 or 3?

I am not at my pc, but hopefully I will be soon!

**Comment by mr-islam** [comment]
I was able to fix that by wrapping the varibles in `str()` from eyecare.py like you said.

Sadly, this creates another issue: now the error message is `Invalid number of options`. At least now it's not a problem with Python. Some searching brought up that [this](http://stackoverflow.com/questions/8850995/notify-send-cause-invalid-number-of-options) similar problem, but I don't see how the answer there helps us :(

But anyway, I'll keep trying stuff, and sorry to constantly bother you haha. Take care!

**Comment by ragerin** [comment]
Hmm, I think I need to run the code myself to see. :-) I will hopefully be
at my computer tomorrow evening.

Don't worry, let's keep up the communication! This is the point of
collaboration!

I'm new to all this too, so I'm learning with you! ;-)

We should put up a Slack channel for talking. :-) I'll try set one up from
my mobile and get back to you in a bit.
